/** Disposable Postgres; deterministic research results, no external requests. */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { CommerceRepository } from '../src/commerce/repository.js';
import { CommerceService } from '../src/commerce/service.js';
const url = process.env.APT_LOCAL_DATABASE_URL ?? '';
assert(URL.canParse(url) && ['127.0.0.1','localhost','[::1]'].includes(new URL(url).hostname));
const pool = new pg.Pool({ connectionString:url });
const A='11111111-1111-4111-8111-111111111111', B='22222222-2222-4222-8222-222222222222';
const PA='apt-aaaaaaaaaaaaaaaaaaaa', PB='apt-bbbbbbbbbbbbbbbbbbbb';
const service = new CommerceService(new CommerceRepository(pool),[A,B],'test');
const act = async (actor:string,id:string,command:unknown) => {
  const e = await service.get(actor,id);
  return service.command(actor,id,randomUUID(),e.revision,command);
};
try {
  const draft = await service.create(A,randomUUID(),{request:{item:'Shoes',style:'White',size:'10',sizingSystem:'US men',condition:'Used good'},privateBudget:937123});
  await assert.rejects(service.research.request(A,draft.id,{kind:'nearby'}),/postcode/);
  await assert.rejects(service.research.request(B,draft.id,{kind:'nearby'}),/not found/);
  await act(A,draft.id,{type:'research_area',postcode:'10001'});
  const [job,replayed] = await Promise.all([service.research.request(A,draft.id,{kind:'nearby'}),service.research.request(A,draft.id,{kind:'nearby'})]);
  assert.equal(job.id,replayed.id);
  await assert.rejects(service.research.request(A,draft.id,{kind:'nearby',query:'PRIVATE'}));
  const lease=(await service.research.outbox(PA)).jobs[0]!;
  assert.equal(lease.id,job.id);
  assert(!JSON.stringify(lease).includes('937123'));
  assert.equal((await service.research.outbox(PA)).jobs.length,0);
  const result={success:true,sources:[{url:'https://locations.theupsstore.com/ny/new-york/209-w-29th-st',title:'UPS source fixture',description:'Fixture only, not proof of service.'}]};
  await assert.rejects(service.research.complete(PB,{id:job.id,leaseId:lease.leaseId,result}),/not found/);
  await assert.rejects(service.research.complete(PA,{id:job.id,leaseId:randomUUID(),result}),/not found/);
  await assert.rejects(service.research.complete(PA,{id:job.id,leaseId:lease.leaseId,result:{success:true,sources:[{url:'https://localhost/private',title:'Unsafe',description:''}]}}));
  await service.research.complete(PA,{id:job.id,leaseId:lease.leaseId,result});
  const sources=(await service.research.list(A,draft.id))[0]!.result!;
  assert.equal(sources.verifiedForFulfillment,false);
  const notificationCount=await pool.query("select count(*)::int n from pilot_messages where exchange_id=$1 and payload->>'action'='research_update'",[draft.id]);
  await service.research.complete(PA,{id:job.id,leaseId:lease.leaseId,result});
  assert.equal((await pool.query("select count(*)::int n from pilot_messages where exchange_id=$1 and payload->>'action'='research_update'",[draft.id])).rows[0].n,notificationCount.rows[0].n);
  await act(A,draft.id,{type:'share_request',requestDigest:draft.requestDigest});
  assert.deepEqual(await service.research.list(B,draft.id),[]);
  const capability = await service.research.request(A,draft.id,{kind:'capabilities',researchId:job.id,sourceId:sources.sources[0]!.id});
  assert(capability.input.query?.startsWith('locations.theupsstore.com official'));
  const second = (await service.research.outbox(PA)).jobs[0]!;
  await service.research.complete(PA,{id:second.id,leaseId:second.leaseId,result:{success:false}});
  assert.equal((await service.research.outbox(PA)).jobs.length,0);
  await pool.query("update pilot_research set attempts=3,updated_at=now()-interval '2 minutes' where id=$1",[second.id]);
  await service.research.outbox(PA);
  assert.equal((await service.research.list(A,draft.id)).find(j=>j.id===second.id)?.state,'failed');
  await assert.rejects(act(B,draft.id,{type:'retry_research',researchId:second.id}),/Only your/);
  await act(A,draft.id,{type:'retry_research',researchId:second.id});
  const third=(await service.research.outbox(PA)).jobs[0]!;
  assert.notEqual(third.leaseId,second.leaseId);
  await assert.rejects(service.research.complete(PA,{id:second.id,leaseId:second.leaseId,result}),/not found/);
  await service.research.complete(PA,{id:third.id,leaseId:third.leaseId,result});
  await act(A,draft.id,{type:'research_area',postcode:'10002'});
  assert((await service.research.list(A,draft.id)).every(r=>!r.currentArea));
  await assert.rejects(service.research.request(A,draft.id,{kind:'read_source',researchId:job.id,sourceId:sources.sources[0]!.id}),/area changed/);
  const live=new CommerceService(service.repository,[A,B],'live');
  await assert.rejects(live.research.list(A,draft.id),/not found/);
  process.stdout.write('PASS: private research, public-query boundaries, idempotency, lease/replay/mode/owner denial, bounded failure/retry and stale-area rejection.\n');
} finally { await pool.end(); }
